# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161218_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
