# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161218_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='email_address_1',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
